---
apiVersion: kbld.k14s.io/v1alpha1
kind: Config

minimumRequiredVersion: 0.15.0

overrides:
- image: fluxcd/source-controller:v1.1.2
  # newImage: projects.registry.vmware.com/tkg/fluxcd/source-controller:v1.1.2_vmware.1
  newImage: harbor-repo.vmware.com/lever/test/fluxcd-source-controller-image:0.0.0-1710941933
