apiVersion: kctrl.carvel.dev/v1alpha1
kind: PackageBuild
metadata:
  creationTimestamp: null
  name: tmc.fluxcd-source-controller.tanzu.vmware.com
spec:
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: projects.registry.vmware.com/tce/fluxcd-source-controller-bundle@sha256:b095202828e66e3561ddc5c642bcdb10ab3d944c159e662abb567698edb0280d
      app:
        spec:
          deploy:
          - kapp: {}
          template:
          - ytt:
              paths:
              - upstream
              - overlays
              - values.yaml
          - kbld:
              paths:
              - "-"
              - .imgpkg/images.yml
      export:
      - includePaths:
        - upstream
        - overlays
        - values.yaml
