apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  creationTimestamp: null
  name: tmc.fluxcd-source-controller.tanzu.vmware.com.0.0.0
spec:
  refName: tmc.fluxcd-source-controller.tanzu.vmware.com
  releasedAt: null
  template:
    spec:
      deploy:
      - kapp: {}
      fetch:
      - git: {}
      template:
      - ytt:
          paths:
          - upstream
          - overlays
          - values.yaml
      - kbld: {}
  valuesSchema:
    openAPIv3: null
  version: 0.0.0

---
apiVersion: data.packaging.carvel.dev/v1alpha1
kind: PackageMetadata
metadata:
  creationTimestamp: null
  name: tmc.fluxcd-source-controller.tanzu.vmware.com
spec:
  displayName: tmc
  longDescription: tmc.fluxcd-source-controller.tanzu.vmware.com
  shortDescription: tmc.fluxcd-source-controller.tanzu.vmware.com

---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  annotations:
    kctrl.carvel.dev/local-fetch-0: .
  creationTimestamp: null
  name: tmc
spec:
  packageRef:
    refName: tmc.fluxcd-source-controller.tanzu.vmware.com
    versionSelection:
      constraints: 0.0.0
  serviceAccountName: tmc-sa
status:
  conditions: null
  friendlyDescription: ""
  observedGeneration: 0
