apiVersion: kctrl.carvel.dev/v1alpha1
kind: PackageBuild
metadata:
  creationTimestamp: null
  name: tmc.fluxcd-source-controller.tanzu.vmware.com
spec:
  template:
    spec:
      app:
        spec:
          deploy:
          - kapp: {}
          template:
          - ytt:
              paths:
              - upstream
              - overlays
              - values.yaml
          - kbld: {}
      export:
      - includePaths:
        - upstream
        - overlays
        - values.yaml
