apiVersion: vendir.k14s.io/v1alpha1
directories:
- contents:
  - git:
      ref: v1.1.2
      url: https://github.com/fluxcd/source-controller
    includePaths:
    - config/**/*
    path: .
    excludePaths: ["config/samples/*", "config/testdata/**", "config/*/kustomization.yaml", "config/rbac/*_editor_role.yaml","config/rbac/*_viewer_role.yaml"]
  path: upstream
kind: Config
minimumRequiredVersion: ""
