---
apiVersion: imgpkg.carvel.dev/v1alpha1
images:
- annotations:
    kbld.carvel.dev/id: fluxcd/source-controller:v1.1.2
    kbld.carvel.dev/origins: |
      - resolved:
          tag: 0.0.0-1710941933
          url: harbor-repo.vmware.com/lever/test/fluxcd-source-controller-image:0.0.0-1710941933
  image: harbor-repo.vmware.com/lever/test/fluxcd-source-controller-image@sha256:86aa40341965c3b1323afd46f85f446b2e023f4184eab30d59867626b5a1a045
kind: ImagesLock
